### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by mapmeld** [neulab/awesome-align#3] opened 2021-02-06 19:51 UTC
I'm trying to finetune on a subtitles corpus. I keep getting a 'list index out of range' error on ```(b2w_src[i], b2w_tgt[j])```, even on some examples in this repo

My command line:

```
! cd awesome-align && CUDA_VISIBLE_DEVICES=0 python run_align.py \
    --output_file=../eval2.txt \
    --model_name_or_path=../my-custom-model \
    --data_file=examples/enfr.src-tgt \
    --extraction 'softmax' \
    --batch_size 32 \
```

The error:

```
Loading the dataset...
Extracting:   0% 0/447 [00:00<?, ?it/s]Traceback (most recent call last):
  File "run_align.py", line 194, in <module>
    main()
  File "run_align.py", line 191, in main
    word_align(args, model, tokenizer)
  File "run_align.py", line 101, in word_align
    word_aligns_list = model.get_aligned_word(ids_src, ids_tgt, bpe2word_map_src, bpe2word_map_tgt, args.device, 0, 0, align_layer=args.align_layer, extraction=args.extraction, softmax_threshold=args.softmax_threshold, test=True)
  File "/content/awesome-align/modeling.py", line 680, in get_aligned_word
    aligns.add( (b2w_src[i], b2w_tgt[j]) )
IndexError: list index out of range
Extracting:   0% 0/447 [00:00<?, ?it/s]
```

I tried shortening arrays but there always seems to be some issue

**Comment by zdou0830** [comment] 2021-02-06 20:34
Thanks for opening the issue!

I tried the command on some of my machines but cannot reproduce the error. Would you mind providing some details of your environment (e.g. pytorch version, python version)?

It may also be helpful if you could print the following variables between line 678 and 679:

```
print(non_zeros) 
print(b2w_src)
print(b2w_tgt)
```

**Comment by mapmeld** [comment] 2021-02-06 21:35
OK I added print and explored further. mBERT handles the example and my custom dataset better, so my custom model/tokenizer appears to be critical to the problem. Here I've reduced batch_size to 2 and skipped earlier successful batches. I believe the issue goes away when batch_size is 1.

non_zeros
```
tensor([[5, 4],
        [6, 5],
        [7, 6],
        [8, 7]], device='cuda:0')
```

b2w_src
```
[0, 0, 0, 1, 2, 3, 4, 5]
```

b2w_tgt
```
[0, 1, 2, 2, 3, 4, 5]
```

Values of i, j at the end here: [tensor(8, device='cuda:0'), tensor(7, device='cuda:0')]

**Comment by zdou0830** [comment] 2021-02-06 21:51
Thanks a lot!

If setting batch_size to 1 can solve this, I think the issue might be with your tokenizer. Here (https://github.com/neulab/awesome-align/blob/master/modeling.py#L543) I hard-coded the bos, eos, pad token ids of BERT (101, 102, 0). The problem might be solved if they are substituted with your corresponding token ids.

**Comment by pjdrm** [comment] 2021-02-12 11:51
I'm experiencing a similar issue but when fine tuning mBERT (`--model_name_or_path=bert-base-multilingual-cased`). Not sure if the root cause is the same since I think the token ids should match in this case. Any insights to help figure out the problem would be great.

**Comment by janissl** [comment] 2021-02-13 16:48
> I'm experiencing a similar issue but when fine tuning mBERT (`--model_name_or_path=bert-base-multilingual-cased`).

Check if there are no empty texts (e.g. just a separator ' ||| ') in your dataFile.

**Comment by pjdrm** [comment] 2021-02-13 18:42
Double checked the file now and no empty lines (not even at the bottom) or just with the separator.

**Comment by zdou0830** [comment] 2021-02-13 19:15
Hi @pjdrm, the root causes should be different. could you clone the `debug` branch (or just make the changes in https://github.com/neulab/awesome-align/commit/0ad236fe794867202e73e9b0566ed98ebeee1a46) and print the detailed error info? that might be helpful, thanks!

**Comment by pjdrm** [comment] 2021-02-16 11:31
@zdou0830 I found the problem. Basically it is what @janissl mentioned but took longer to figure out because the offending line was using a non-conventional whitespace char. The debug branch definitely helped to spot this. Thanks for the help!

**Comment by zdou0830** [comment] 2021-02-26 22:45
Handled this in https://github.com/neulab/awesome-align/commit/43651735d420e73b0d01ff3b47c7e2d72c63e9dc and i'm closing the issue for now.

**Closed by zdou0830** 2021-02-26 22:45 UTC
